(function() {var implementors = {};
implementors["cumulus_test_runtime"] = [{"text":"impl&lt;Block:&nbsp;BlockT, C:&nbsp;CallApiAt&lt;Block&gt;&gt; ApiExt&lt;Block&gt; for <a class=\"struct\" href=\"cumulus_test_runtime/struct.RuntimeApiImpl.html\" title=\"struct cumulus_test_runtime::RuntimeApiImpl\">RuntimeApiImpl</a>&lt;Block, C&gt;","synthetic":false,"types":["cumulus_test_runtime::RuntimeApiImpl"]}];
implementors["parachain_template_runtime"] = [{"text":"impl&lt;Block:&nbsp;BlockT, C:&nbsp;CallApiAt&lt;Block&gt;&gt; ApiExt&lt;Block&gt; for <a class=\"struct\" href=\"parachain_template_runtime/struct.RuntimeApiImpl.html\" title=\"struct parachain_template_runtime::RuntimeApiImpl\">RuntimeApiImpl</a>&lt;Block, C&gt;","synthetic":false,"types":["parachain_template_runtime::RuntimeApiImpl"]}];
implementors["rococo_parachain_runtime"] = [{"text":"impl&lt;Block:&nbsp;BlockT, C:&nbsp;CallApiAt&lt;Block&gt;&gt; ApiExt&lt;Block&gt; for <a class=\"struct\" href=\"rococo_parachain_runtime/struct.RuntimeApiImpl.html\" title=\"struct rococo_parachain_runtime::RuntimeApiImpl\">RuntimeApiImpl</a>&lt;Block, C&gt;","synthetic":false,"types":["rococo_parachain_runtime::RuntimeApiImpl"]}];
implementors["seedling_runtime"] = [{"text":"impl&lt;Block:&nbsp;BlockT, C:&nbsp;CallApiAt&lt;Block&gt;&gt; ApiExt&lt;Block&gt; for <a class=\"struct\" href=\"seedling_runtime/struct.RuntimeApiImpl.html\" title=\"struct seedling_runtime::RuntimeApiImpl\">RuntimeApiImpl</a>&lt;Block, C&gt;","synthetic":false,"types":["seedling_runtime::RuntimeApiImpl"]}];
implementors["shell_runtime"] = [{"text":"impl&lt;Block:&nbsp;BlockT, C:&nbsp;CallApiAt&lt;Block&gt;&gt; ApiExt&lt;Block&gt; for <a class=\"struct\" href=\"shell_runtime/struct.RuntimeApiImpl.html\" title=\"struct shell_runtime::RuntimeApiImpl\">RuntimeApiImpl</a>&lt;Block, C&gt;","synthetic":false,"types":["shell_runtime::RuntimeApiImpl"]}];
implementors["statemine_runtime"] = [{"text":"impl&lt;Block:&nbsp;BlockT, C:&nbsp;CallApiAt&lt;Block&gt;&gt; ApiExt&lt;Block&gt; for <a class=\"struct\" href=\"statemine_runtime/struct.RuntimeApiImpl.html\" title=\"struct statemine_runtime::RuntimeApiImpl\">RuntimeApiImpl</a>&lt;Block, C&gt;","synthetic":false,"types":["statemine_runtime::RuntimeApiImpl"]}];
implementors["statemint_runtime"] = [{"text":"impl&lt;Block:&nbsp;BlockT, C:&nbsp;CallApiAt&lt;Block&gt;&gt; ApiExt&lt;Block&gt; for <a class=\"struct\" href=\"statemint_runtime/struct.RuntimeApiImpl.html\" title=\"struct statemint_runtime::RuntimeApiImpl\">RuntimeApiImpl</a>&lt;Block, C&gt;","synthetic":false,"types":["statemint_runtime::RuntimeApiImpl"]}];
implementors["westmint_runtime"] = [{"text":"impl&lt;Block:&nbsp;BlockT, C:&nbsp;CallApiAt&lt;Block&gt;&gt; ApiExt&lt;Block&gt; for <a class=\"struct\" href=\"westmint_runtime/struct.RuntimeApiImpl.html\" title=\"struct westmint_runtime::RuntimeApiImpl\">RuntimeApiImpl</a>&lt;Block, C&gt;","synthetic":false,"types":["westmint_runtime::RuntimeApiImpl"]}];
if (window.register_implementors) {window.register_implementors(implementors);} else {window.pending_implementors = implementors;}})()