[package]
name = "cumulus-primitives-parachain-inherent"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
# Substrate dependencies
sp-inherents = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.4" }
sp-core = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.4" }
sc-client-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4", optional = true }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4", optional = true }
sp-std = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.4" }
sp-state-machine = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4", optional = true }
sp-trie = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.4" }
sp-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4", optional = true }

# Polkadot dependencies
polkadot-service = { git = "https://github.com/paritytech/polkadot", optional = true, branch = "release-v0.9.4" }

# Cumulus dependencies
cumulus-primitives-core = { path = "../core", default-features = false }

# Other dependencies
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = [ "derive" ] }
tracing = { version = "0.1.22", optional = true }
async-trait = { version = "0.1.42", optional = true }

[features]
default = [ "std" ]
std = [
	"async-trait",
	"codec/std",
	"cumulus-primitives-core/std",
	"sp-inherents/std",
	"sp-core/std",
	"sp-trie/std",
	"sp-std/std",
	"sp-state-machine",
	"tracing",
	"sp-runtime",
	"sc-client-api",
	"sp-api",
	"polkadot-service",
]
